### ISSUE TITLE
deleting a cell in gi-to-pi Studio causes exception

### ISSUE THREAD

**Issue by joanise** [roedoejet/g2p#12]
when using the Gⁱ-to-Pⁱ Studio, if you hit the Delete key or using Ctrl-X inside the Custom Rules spreadsheet, you get an Exception.

Trace, after entering `a`, `e` and hitting Delete in the context before column, with `fae` as the text to map.

Notice the `["a","e",null,""]` in the mappings, which causes the problem.

```
INFO - 276110fdfcbf46859a87a2bb5a24c5a0: Received packet MESSAGE data 2/convert,["conversion event",{"data":{"input_string":"fae","mappings":[["a","e",null,""],["","","",""],["","","",""],["","","",""],["","","",""],["","","",""],["","","",""],["","","",""],["","","",""],["","","",""]],"abbreviations":[["Vowels","a","e","i","o","u"],["","","","","",""],["","","","","",""],["","","","","",""],["","","","","",""],["","","","","",""],["","","","","",""],["","","","","",""],["","","","","",""],["","","","","",""],["","","","","",""]],"kwargs":{"as_is":true,"case_sensitive":true,"escape_special":false,"reverse":false}}}]
INFO - received event "conversion event" from 276110fdfcbf46859a87a2bb5a24c5a0 [/convert]
INFO - 142.98.46.127 - - [26/Sep/2019 15:18:00] "POST /socket.io/?EIO=3&transport=polling&t=Mrl0Zmn&sid=276110fdfcbf46859a87a2bb5a24c5a0 HTTP/1.1" 200 -
Exception in thread Thread-24:
Traceback (most recent call last):
  File "/home/joa125/u/anaconda3/envs/ilt/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/home/joa125/u/anaconda3/envs/ilt/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/joa125/u/anaconda3/envs/ilt/lib/python3.7/site-packages/socketio/server.py", line 648, in _handle_event_internal
    r = server._trigger_event(data[0], namespace, sid, *data[1:])
  File "/home/joa125/u/anaconda3/envs/ilt/lib/python3.7/site-packages/socketio/server.py", line 677, in _trigger_event
    return self.handlers[namespace][event](*args)
  File "/home/joa125/u/anaconda3/envs/ilt/lib/python3.7/site-packages/flask_socketio/__init__.py", line 277, in _handler
    *args)
  File "/home/joa125/u/anaconda3/envs/ilt/lib/python3.7/site-packages/flask_socketio/__init__.py", line 680, in _handle_event
    ret = handler(*args)
  File "/gpfs/fs1/nrc/ict/others/u/joa125/sandboxes/readalong/g2p/g2p/__init__.py", line 94, in convert
    message['data']['abbreviations']), **message['data']['kwargs'])
  File "/gpfs/fs1/nrc/ict/others/u/joa125/sandboxes/readalong/g2p/g2p/mappings/__init__.py", line 82, in __init__
    if key in ['in', 'out', 'context_before', 'context_after'] and re.search(abb_match, io[key]):
  File "/home/joa125/u/anaconda3/envs/ilt/lib/python3.7/re.py", line 183, in search
    return _compile(pattern, flags).search(string)
TypeError: expected string or bytes-like object
```

**Comment by roedoejet** [comment]
Fixed here: 246daa389910265e992f6f727844b0ce1bedfd60
