### ISSUE TITLE
g2p is not currently compatible with Python 3.10 - because of eventlet

### ISSUE THREAD

**Issue by joanise** [roedoejet/g2p#137]
Summary: it appears that neither eventlet 0.30.2 nor the latest are compatible with Python 3.10, or possibly with some of the library versions we require in g2p.

setup:
```
conda create -p ./conda-venv-3.10-ras python==3.10.0
conda activate ./conda-venv-3.10-ras
conda install ffmpeg
pip install g2p
```
command that errors out (simpler yet: `python -c "import eventlet"` shows the same error):
```
$ g2p -h
Traceback (most recent call last):
  File "/home/joanise/conda-venv-3.10-ras/bin/g2p", line 5, in <module>
    from g2p.cli import cli
  File "/home/joanise/conda-venv-3.10-ras/lib/python3.10/site-packages/g2p/cli.py", line 13, in <module>
    from g2p.app import APP, network_to_echart
  File "/home/joanise/conda-venv-3.10-ras/lib/python3.10/site-packages/g2p/app.py", line 13, in <module>
    from flask_socketio import SocketIO, emit
  File "/home/joanise/conda-venv-3.10-ras/lib/python3.10/site-packages/flask_socketio/__init__.py", line 9, in <module>
    from socketio import socketio_manage  # noqa: F401
  File "/home/joanise/conda-venv-3.10-ras/lib/python3.10/site-packages/socketio/__init__.py", line 9, in <module>
    from .zmq_manager import ZmqManager
  File "/home/joanise/conda-venv-3.10-ras/lib/python3.10/site-packages/socketio/zmq_manager.py", line 5, in <module>
    import eventlet.green.zmq as zmq
  File "/home/joanise/conda-venv-3.10-ras/lib/python3.10/site-packages/eventlet/__init__.py", line 17, in <module>
    from eventlet import convenience
  File "/home/joanise/conda-venv-3.10-ras/lib/python3.10/site-packages/eventlet/convenience.py", line 7, in <module>
    from eventlet.green import socket
  File "/home/joanise/conda-venv-3.10-ras/lib/python3.10/site-packages/eventlet/green/socket.py", line 4, in <module>
    __import__('eventlet.green._socket_nodns')
  File "/home/joanise/conda-venv-3.10-ras/lib/python3.10/site-packages/eventlet/green/_socket_nodns.py", line 11, in <module>
    from eventlet import greenio
  File "/home/joanise/conda-venv-3.10-ras/lib/python3.10/site-packages/eventlet/greenio/__init__.py", line 3, in <module>
    from eventlet.greenio.base import *  # noqa
  File "/home/joanise/conda-venv-3.10-ras/lib/python3.10/site-packages/eventlet/greenio/base.py", line 32, in <module>
    socket_timeout = eventlet.timeout.wrap_is_timeout(socket.timeout)
  File "/home/joanise/conda-venv-3.10-ras/lib/python3.10/site-packages/eventlet/timeout.py", line 166, in wrap_is_timeout
    base.is_timeout = property(lambda _: True)
TypeError: cannot set 'is_timeout' attribute of immutable type 'TimeoutError'
```

Attempt at a quick fix:
```
$ pip install --upgrade eventlet
$ g2p -h
Traceback (most recent call last):
  File "/home/joanise/conda-venv-3.10-ras/bin/g2p", line 5, in <module>
    from g2p.cli import cli
  File "/home/joanise/conda-venv-3.10-ras/lib/python3.10/site-packages/g2p/cli.py", line 13, in <module>
    from g2p.app import APP, network_to_echart
  File "/home/joanise/conda-venv-3.10-ras/lib/python3.10/site-packages/g2p/app.py", line 13, in <module>
    from flask_socketio import SocketIO, emit
  File "/home/joanise/conda-venv-3.10-ras/lib/python3.10/site-packages/flask_socketio/__init__.py", line 9, in <module>
    from socketio import socketio_manage  # noqa: F401
  File "/home/joanise/conda-venv-3.10-ras/lib/python3.10/site-packages/socketio/__init__.py", line 9, in <module>
    from .zmq_manager import ZmqManager
  File "/home/joanise/conda-venv-3.10-ras/lib/python3.10/site-packages/socketio/zmq_manager.py", line 5, in <module>
    import eventlet.green.zmq as zmq
  File "/home/joanise/conda-venv-3.10-ras/lib/python3.10/site-packages/eventlet/__init__.py", line 17, in <module>
    from eventlet import convenience
  File "/home/joanise/conda-venv-3.10-ras/lib/python3.10/site-packages/eventlet/convenience.py", line 7, in <module>
    from eventlet.green import socket
  File "/home/joanise/conda-venv-3.10-ras/lib/python3.10/site-packages/eventlet/green/socket.py", line 21, in <module>
    from eventlet.support import greendns
  File "/home/joanise/conda-venv-3.10-ras/lib/python3.10/site-packages/eventlet/support/greendns.py", line 66, in <module>
    setattr(dns, pkg, import_patched('dns.' + pkg))
  File "/home/joanise/conda-venv-3.10-ras/lib/python3.10/site-packages/eventlet/support/greendns.py", line 61, in import_patched
    return patcher.import_patched(module_name, **modules)
  File "/home/joanise/conda-venv-3.10-ras/lib/python3.10/site-packages/eventlet/patcher.py", line 132, in import_patched
    return inject(
  File "/home/joanise/conda-venv-3.10-ras/lib/python3.10/site-packages/eventlet/patcher.py", line 109, in inject
    module = __import__(module_name, {}, {}, module_name.split('.')[:-1])
  File "/home/joanise/conda-venv-3.10-ras/lib/python3.10/site-packages/dns/namedict.py", line 35, in <module>
    class NameDict(collections.MutableMapping):
AttributeError: module 'collections' has no attribute 'MutableMapping'
```

**Comment by joanise** [comment]
It's got something to do with interactions between our dependencies.

Just tested eventlet on its own:
```
conda create -p conda-venv-3.10-eventlet python==3.10.0
conda activate /home/joanise/conda-venv-3.10-eventlet
pip install eventlet
python -c "import eventlet"
```
works without errors.

**Comment by joanise** [comment]
Possible fix:
```
pip install --upgrade dnspython
pip install --upgrade eventlet
```
and then `g2p -h` works.

But then we might have trouble with whatever it is that's blocking us from upgrading eventlet...

**Comment by roedoejet** [comment]
Fixed with https://github.com/roedoejet/g2p/pull/138
