### ISSUE TITLE
command line errors should give helpful error messages

### ISSUE THREAD

**Issue by joanise** [roedoejet/g2p#28]
Currently, if I type `g2p convert frygt dan`, forgetting OUT_LANG, or `g2p convert frygt`, leaving both IN_LANG and OUT_LANG out, I get this exception:

```
$ g2p convert frygt dan
INFO - Server initialized for eventlet.
Traceback (most recent call last):
  File "C:\Users\joanise\RAS\ras-env\Scripts\g2p-script.py", line 11, in <module>
    load_entry_point('g2p', 'console_scripts', 'g2p')()
  File "c:\users\joanise\ras\ras-env\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\joanise\ras\ras-env\lib\site-packages\flask\cli.py", line 557, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "c:\users\joanise\ras\ras-env\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\users\joanise\ras\ras-env\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\joanise\ras\ras-env\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\joanise\ras\ras-env\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\users\joanise\ras\ras-env\lib\site-packages\click\decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\users\joanise\ras\ras-env\lib\site-packages\flask\cli.py", line 412, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "c:\users\joanise\ras\ras-env\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\users\joanise\ras\g2p\g2p\cli.py", line 76, in convert
    tg = transducer(input_text)
UnboundLocalError: local variable 'transducer' referenced before assignment
```

Instead, I should get an error message that says IN_LANG and OUT_LANG are missing, similar to the message produced when I run `g2p convert` with no arguments at all:

```
$ g2p convert
INFO - Server initialized for eventlet.
Usage: g2p convert [OPTIONS] INPUT_TEXT [IN_LANG] [OUT_LANG]
Try "g2p convert --help" for help.

Error: Missing argument "INPUT_TEXT".
```

**Comment by roedoejet** [comment]
There's probably more work to be done wrt error messaging, but at least proper messages should be given for required arguments now as of b384bfe

**Comment by joanise** [comment]
This is perfect, the error message is explicit and outputs the usage again. Thanks!
